# Generated by Django 5.1.3 on 2024-11-25 07:31

import App.data.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Entry name', max_length=255)),
                ('csv', models.FileField(upload_to='uploads/zips/', validators=[App.data.models.validate_zip])),
                ('videos', models.FileField(upload_to='uploads/zips/', validators=[App.data.models.validate_zip])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
